### ISSUE TITLE
ZP jen tak - vícestránkový životopis

### ISSUE THREAD

**Issue by IxAriela** [8venom8/01.ukol-zivotopis#1]
Dobrá práce, s tím musela být makačka :)

Ve tvém případě by stačilo dát místo position: fixed; position: absolute; - tady vysvětlen pěkně rozdíl https://www.jakpsatweb.cz/css/position.html

Bohužel je ale ukotvení obsahu k pozadí dost problematické. V součastnosti už jsou responsivní stránky v podstatě nutnost a tam už ti to tak jak to máš stačit nebude. Dalo by se to zhruba udělat pomocí % a obrázku jako contain, ale ani tam není zaručeno že to bude sedět. Nebo taky celé obrázkem, včetně textu, a pozicováním pouze odkazu, ten není vidět, takže když se trošku posune, tak to nemusí tolik vadit. Jenže tohle taky není ideální, úpravy textu se dost zesložití a navíc ten text nepřečte vyhledávač nebo třeba čtečka pro nevidomé (u menu dost důležité).

Na kod jsem koukla jen v rychlosti v prohlížeči. Section je označení určité části, takže na vícestránkovém webu je to většinou obal té části mezi záhlavím a zápatím. Určitě se nehodí tím označovat kroužky, na to jsou divy nebo spany :) 

Po přečtení to issue klidně zavři. Nech mi to otevřené jedině, kdybys chtěla , abych se na to mrkla víc a dej vědět, ale teď se mi to dost nakupilo, tak by to určitě trvalo.

**Comment by 8venom8** [comment]
Je děkuju to mě potěšilo :) Pustila jsem se do toho po hlavě, aniž bych to více promyslela a dost jsem se zasekla. Alespoň jsem si to procvičila, když už nic.  Děkuju za rady :) přečtu si a vyhledám si vše výše zmíněné. Issue tedy zavírám :)
